jira:
  server: ${JIRA_SERVER}
  email: ${JIRA_EMAIL}
  api_token: ${JIRA_API_TOKEN}
  
assignment:
  assignee_email: ${ASSIGNEE_EMAIL}
  project_key: ${PROJECT_KEY}
  
polling:
  interval_seconds: 30  # How often to check for new tickets
